baseURL: "https://www.vecko.me"
languageCode: "en-us"
author:
  name: Nick Hodgskin
title: Vecko

taxonomies:
  tag: tags
  category: categories
  series: series

menu:
  nav:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 2

markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
